server:
  port: ${ALERT_SERVICE_PORT}

grpc:
  server:
    port: ${ALERT_SERVICE_PORT}

spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT}
      username: ${MONGO_USER}
      password: ${MONGO_PASSWORD}
      database: alerts_db
      authentication-database: admin

management:
  endpoints:
    web:
      exposure:
        include: health,info