spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_AUTH_SERVICE_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

# gRPC
grpc:
  server:
    port: ${USER_SERVICE_PORT}
    address: localhost

# Server
server:
  port: ${USER_SERVICE_PORT}

# Logging
logging:
  level:
    root: INFO
    com.codistrib.userservice: DEBUG