spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_USER_SERVICE_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

# gRPC
grpc:
  server:
    port: ${USER_SERVICE_PORT}
    address: 0.0.0.0  # Ã‰coute sur toutes les interfaces
  client:
    auth-service:
      host: auth-service
      port: ${AUTH_SERVICE_PORT}

# Server
server:
  port: ${USER_SERVICE_PORT}

# Logging
logging:
  level:
    root: INFO
    com.codistrib.userservice: INFO